# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create7 any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tumble Network CSS
description: > # this means to ignore newlines until "baseurl:"
  My Github Website
url: "https://tumblenet.github.io/tumblenet-css-public-beta" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
production: true
favicon: favicon.gif



collections:

gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-seo-tag


# Build settings
markdown: kramdown
# theme: minima
excludes:
  - lib
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower.json
  - "*.sh"
  - README.md
  - gulffile.js
  - package.json
  - vendor
